name: starter_project
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  approval_tests: 0.3.8
    # path: ../../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
