part of '../../../approval_tests.dart';

final class ApprovalTestsConstants {
  static const String widgetHeader = '''
# This file was autogenerated by package:approval_tests_flutter. Please do not edit.
# Below is a list of class found in the project /lib folder.''';

  static const String baseHeader = '''
# This file was generated by approval_tests. Please do not edit.\n''';

  static const resourceLocalPath = './test/.approval_tests';
  static const receivedFilesPath = '$resourceLocalPath/received_files.txt';
}
