name: dart_application
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  approval_tests:
    path: ../../

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
