name: Check Release Tag

on:
  workflow_run:
    workflows: ["Build and test"]
    types:
      - completed

jobs:
  check-release-tag:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Check release tag
        run: |
          ./bash/push_release.sh
        shell: bash
